(ns cosheet2.entity-test
  (:require [clojure.test :refer [deftest is]]
            (cosheet2 [orderable :as orderable]
                      [reporter :refer [valid? set-attendee!
                                        reporter-value]]
                      [expression :refer [expr-let]]
                      [store :refer [add-link make-item-id get-new-object-id
                                     new-element-store new-mutable-store
                                     track-modified-ids
                                     current-store
                                     update-source store-update!]]
                      store-impl
                      mutable-store-impl
                      [entity :refer :all]
                      [entity-impl :as entity-impl]
                      [calculator :refer [current-value new-calculator-data
                                          propagate-calculator-data!]]
                      [canonical :refer [canonicalize]]
                      [task-queue :refer [new-priority-task-queue
                                          run-all-pending-tasks]]
                      [test-utils :refer [check any as-set]])
            ; :reload
            ))

;;; This tests the internal function of entity-impl
(deftest entity<->endpoint-test
  (let [[s id] (add-link (new-element-store) (make-item-id "a") "B")
        item (id->element id s)
        reversed-item (id->element id :target s)]
    (is (= (entity-impl/endpoint->entity 2 s) 2))
    (is (= (entity-impl/endpoint->entity :foo s) :foo))
    (is (= (entity-impl/endpoint->entity 'foo s) 'foo))
    (is (= (entity-impl/endpoint->entity orderable/initial s)
           orderable/initial))
    (is (= (entity-impl/endpoint->entity "1" s) "1"))
    (is (= (entity-impl/endpoint->entity id s) item))
    (is (= (entity-impl/endpoint->entity id s :target) reversed-item))))

(deftest id-only-item-test
  (let [[sa id0] (get-new-object-id (new-element-store))
        [_ id1] (get-new-object-id sa)
        id99 (make-item-id "99")
        item0 (id->object id0 nil)
        item1 (id->object id1 nil)
        item99 (id->object id99 nil)]
    (is (= (:item-id  item0) id0))
    (is (= (:item-id  item99) id99))
    (is (not (primitive? item0)))
    (is (object? item0))
    (is (not (element? item0)))
    (is (non-identified-object? item0))
    (is (not (uniquely-identified-object? item0)))
    (is (= (orientation item0)) nil)
    (is (= (target-entity item0) nil))
    (is (= (label->elements item99 "foo") nil))
    (is (= (elements item99) nil))
    (is (= (forward-elements item99) nil))
    (is (= (content item99) nil))
    (is (not (marked-as-type? item99)))
    (is (= (content->elements item99 4) nil))
    (is (= (label->elements item99 "foo") nil))
    (is (= (entity-key item99) id99))
    (is (= (to-list item0) (make-object-list nil)))
    (is (= (to-list item99) item99))))

(deftest storeditem-test
  (let [[sa id0] (get-new-object-id (new-element-store))
        id1 (make-item-id "1")
        [sc id99] (get-new-object-id sa)
        [s1 ida] (add-link sc id99 3)
        [s2 idb] (add-link s1 ida "foo")
        [s3 idc] (add-link s2 id99 4)
        [s4 idd] (add-link s3 idc "bar")
        [s5 ide] (add-link s4 id99 "baz")
        [s6 idg] (add-link s5 ide "bletch")
        [s7 idh] (add-link s6 idb :label)
        [s8 idi] (add-link s7 id99 "Joe")
        [s9 idj] (add-link s8 idi (make-item-id "name"))
        [s11 idl] (add-link s9 id0 "irrelevant")
        [s12 idm] (add-link s11 id0 id1)
        [s13 idn] (add-link s12 idm "relationship")
        [s ido] (add-link s13 idn :label)
        item0 (id->object id0 s)
        item1 (id->object id1 s)
        item99 (id->object id99 s)
        list-99 '[:object ("baz" "bletch")
                          (4 "bar")
                          (3 ("foo" :label))
                  :generic]
        item-a (id->element ida s)
        item-b (id->element idb s)
        item-m (id->element idm s)
        item-a-reversed (id->element ida :target s)
        item-b-reversed (id->element idb :target s)]
    (is (= (:item-id  item0) id0))
    (is (= (:item-id  item1) id1))
    (is (not (primitive? item0)))
    (is (object? item0))
    (is (not (object? item-b)))
    (is (uniquely-identified-object? item99))
    (is (uniquely-identified-object? (id->object (make-item-id "foo") s)))
    (is (not (uniquely-identified-object? item-b)))
    (is (not (uniquely-identified-object? item0)))
    (is (not (uniquely-identified-object? "foo")))
    (is (non-identified-object? item0))
    (is (not (non-identified-object? item-b)))
    (is (not (non-identified-object? item99)))
    (is (not (non-identified-object? (id->object (make-item-id "foo") s))))
    (is (not (non-identified-object? "foo")))
    (is (= (orientation item0)) nil)
    (is (= (orientation item-b)) :source)
    (is (= (orientation item-a-reversed)) :target)
    (is (= (target-entity (id->element ida s)) item99))
    (is (= (target-entity item-a-reversed) item99))
    (is (= (target-entity item-b-reversed) (id->element ida s)))
    (is (= (label->elements item99 "foo") [(id->element ida s)]))
    ;; Check that the :label is required.
    (is (= (label->elements (id->object id99 s5) "foo") nil))
    ;; Check that we pick up relationships both forwards and backwards.
    (is (= (label->elements item0 "relationship")
           [(id->element idm s)]))
    (is (= (label->elements item1 "relationship")
           [(id->element idm :target s)]))
    (is (= (set (elements item99))
           #{(id->element ida s)
             (id->element idc s)
             (id->element ide s)
             (id->element idi s)}))
    (is (= (set (forward-elements item99))
           #{(id->element ida s)
             (id->element idc s)
             (id->element ide s)
             (id->element idi s)}))
    (is (= (elements (id->element idd s))
           nil))
    (is (= (forward-elements (id->element idd s))
           nil))
    (is (= (content item99) nil))
    (is (marked-as-type? item-b))
    (is (not (marked-as-type? item99)))
    (is (= (content (id->element ida s)) 3))
    (is (= (content item-b) "foo"))
    (is (= (content item-a-reversed) item99))
    (is (= (content->elements item99 4) [(id->element idc s)]))
    (is (= (content->elements item-a "foo") [(id->element idb s)]))
    (is (= (content->elements item0 item1) [(id->element idm s)]))
    (is (= (content->elements item1 item0) [(id->element idm :target s)]))
    (is (= (label->element item99 "foo") (id->element ida s)))
    (is (= (label->element item99 "bletch") nil))
    (is (= (label->content item99 "foo") 3))
    (is (= (label->content item99 "bletch") nil))
    (let [[sx idx] (add-link s id99 7)
          [sy idy] (add-link sx idx "foo")
          [sz idz] (add-link sy idy :label)]
      (is (thrown? java.lang.AssertionError
                   (label->element (id->object id99 sz) "foo")))
      (is (thrown? java.lang.AssertionError
                   (label->content (id->object id99 sz) "foo"))))
    (is (= (content (id->element idc s)) 4))
    (is (= (content item-a-reversed) item99))
    (is (= (content item-b-reversed) item-a-reversed))
    (is (= (entity-key item-a) ida))
    (is (= (entity-key item-a-reversed) ida))
    (is (= (to-list item99) item99))
    (is (check (elements item0)
               (as-set [(id->element idl s)
                        (id->element idm s)])))
    (is (check (forward-elements item0)
               (as-set [(id->element idl s)
                        (id->element idm s)])))
    (is (check (elements item1)
               (as-set [(id->element idm :target s)])))
    (is (= (forward-elements item1)
           nil))
    (is (check (to-list item1) item1))
    (is (= (to-list item-a-reversed) `((:target ~item99) ("foo" :label))))
    (is (= (to-list item-m) (make-element-list :source item1
                                               '(("relationship" :label)))))
    (is (check (to-list item0)
               (as-set (make-object-list
                        `(~(make-element-list :source item1
                                              '(("relationship" :label)))
                          "irrelevant")))))))

(deftest mutable-storeditem-test
  (let [[sa id0] (get-new-object-id (new-element-store))
        id1 (make-item-id "1")
        [sc id99] (get-new-object-id sa)
        [s1 ida] (add-link sc id99 3)
        [s2 idb] (add-link s1 ida "foo")
        [s3 idc] (add-link s2 id99 4)
        [s4 idd] (add-link s3 idc "bar")
        [s5 ide] (add-link s4 id99 "baz")
        [s6 idg] (add-link s5 ide "bletch")
        [s7 idh] (add-link s6 idb :label)
        [s8 idi] (add-link s7 id99 "Joe")
        [s9 idj] (add-link s8 idi (make-item-id "name"))
        [s11 idl] (add-link s9 id0 "irrelevant")
        [s12 idm] (add-link s11 id0 id1)
        [s13 idn] (add-link s12 idm "relationship")
        [s ido] (add-link s13 idn :label)
        queue (new-priority-task-queue 0)
        cd (new-calculator-data queue)
        ms (new-mutable-store s)
        item0 (id->object id0 ms)
        item1 (id->object id1 ms)
        item99 (id->object id99 ms)
        list-99 `[:object ("baz" "bletch")
                          (4 "bar")
                          (3 ("foo" :label))
                          :generic]
        item-a (id->element ida ms)
        item-b (id->element idb ms)
        item-a-reversed (id->element ida :target ms)
        item-b-reversed (id->element idb :target ms)]
    (is (= (:item-id  item0) id0))
    (is (= (:item-id  item1) id1))
    (is (not (element? item0)))
    (is (element? item-b))
    (is (object? item0))
    (is (not (object? item-b)))
    (is (= (orientation item0)) nil)
    (is (= (orientation item-b)) :source)
    (is (= (orientation item-a-reversed)) :target)
    (is (= (current-value (target-entity (id->element ida ms))) item99))
    (is (= (current-value (target-entity item-a-reversed)) item99))
    (is (= (current-value (target-entity item-b-reversed)) (id->element ida ms)))
    (is (= (primitive? item0) false))
    (is (= (current-value (label->elements item99 "foo"))
           [(id->element ida ms)]))
    (is (= (current-value (label->elements item99 "bar")) nil))
    ;; Check that we pick up relationships both forwards and backwards.
    (is (= (current-value (label->elements item0 "relationship"))
           [(id->element idm ms)]))
    (is (= (current-value (label->elements item1 "relationship"))
           [(id->element idm :target ms)]))
    (is (= (set (current-value (elements item99)))
           #{(id->element ida ms)
             (id->element idc ms)
             (id->element ide ms)
             (id->element idi ms)}))
    (is (= (set (current-value (forward-elements item99)))
           #{(id->element ida ms)
             (id->element idc ms)
             (id->element ide ms)
             (id->element idi ms)}))
    (is (= (current-value (elements (id->element idd ms)))
           nil))
    (is (= (current-value (forward-elements (id->element idd ms)))
           nil))
    (is (= (current-value (content item99)) nil))
    (is (= (current-value (content item-a-reversed)) item99))
    (is (= (current-value (content item-b-reversed)) item-a-reversed))
    (is (= (current-value (content->elements item99 4))
           [(id->element idc ms)]))
    (is (= (current-value (content->elements item-a "foo"))
           [(id->element idb ms)]))
    (is (= (current-value (content->elements item0 item1))
           [(id->element idm ms)]))
    (is (= (current-value (content->elements item1 item0))
           [(id->element idm :target ms)]))
    (is (current-value (marked-as-type? item-b)))
    (is (not (current-value (marked-as-type? item99))))
    (is (= (current-value (content (id->element ida ms))) 3))
    (is (= (current-value (content item-a-reversed)) item99))
    (is (current-value
         [content (current-value (content (id->element idc ms)))])
        4)
    (is (= (current-value (content->elements item99 4))
           [(id->element idc ms)]))
    (is (= (current-value (label->content item99 "foo")) 3))
    (is (= (current-value (label->content item99 "bletch")) nil))
    (is (= (current-value (content (id->element idc ms))) 4))
    (is (= (entity-key item-a) ida))
    (is (= (entity-key item-a-reversed) ida))
    (is (= (current-value (to-list item99))
           item99))
    (is (= (current-value (to-list item-a-reversed))
           `((:target ~item99) ("foo" :label))))
    (is (check (current-value (elements item0))
               (as-set [(id->element idl ms)
                        (id->element idm ms)])))
    (is (check (current-value (forward-elements item0))
               (as-set [(id->element idl ms)
                        (id->element idm ms)])))
    (is (check (current-value (elements item1))
               (as-set [(id->element idm :target ms)])))
    (is (= (current-value (forward-elements item1))
           nil))
    ;; Now make sure updating-immutable tracks right.
    (let [record-of-updates (atom [])
          updating-immutable-result (expr-let [current-item (updating-immutable
                                                             item99)] 
                                      (is (not (mutable-entity? current-item)))
                                      (let [value (to-list current-item)]
                                        (swap! record-of-updates
                                               #(conj % value))
                                        value))
          reporter-99 (id->updating-entity-R id99 ms)]
      (is (= @record-of-updates []))
      ;; See if it gets computed when demand is added.
      (propagate-calculator-data! updating-immutable-result cd)
      (propagate-calculator-data! reporter-99 cd)
      (run-all-pending-tasks queue)
      (is (not (valid? updating-immutable-result)))
      (set-attendee! updating-immutable-result :a 0 (fn [& _] nil))
      (set-attendee! reporter-99 :a 0 (fn [& _] nil))
      (is (not (valid? updating-immutable-result)))
      (run-all-pending-tasks queue)
      (let [orig-99 (to-list (in-different-store item99 (current-store ms)))]
        (is (check (canonicalize
                    (reporter-value updating-immutable-result))
                   (canonicalize orig-99)))
        (is (check (map canonicalize @record-of-updates)
                   [(canonicalize orig-99)]))
        ;; Make sure it is not recomputed when an irrelevant change is made.
        (store-update! ms (fn [s] (update-source s idj 44)))
        (is (check (map canonicalize @record-of-updates)
                   [(canonicalize orig-99)]))
        ;; Make sure it is recomputed when a deep, but relevant, change is made.
        (store-update! ms (fn [s] (update-source s idd "bletch")))
        (run-all-pending-tasks queue)
        (is (check (canonicalize
                    (reporter-value updating-immutable-result))
                   (canonicalize
                    (to-list (in-different-store item99 (current-store ms))))))
        (is (check (canonicalize
                    (to-list (reporter-value reporter-99)))
                   (canonicalize
                    (to-list (in-different-store item99 (current-store ms))))))
        (is (check (map canonicalize @record-of-updates)
                   [(canonicalize orig-99)
                    (canonicalize
                     (to-list (in-different-store item99
                                                  (current-store ms))))]))))))

(deftest list-test
  (is (not (primitive? '(1 2))))
  (is (element? '(1 2)))
  (is (not (object? '(1 2))))
  (is (= (orientation '(1 2)) :source))
  (is (= (orientation '((:target 1) 2)) :target))
  (is (= (elements '(1 2)) [2]))
  (is (= (forward-elements '(1 2)) [2]))
  (is (= (elements '(1 (2 3) (4 5))) '[(2 3) (4 5)]))
  (is (= (forward-elements '(1 (2 3) (4 5))) '[(2 3) (4 5)]))
  (is (= (label->elements '(1 (2 (3 :label)) (4 3)) 3)
         '[(2 (3 :label))]))
  (is (= (content '(1 (2 3) (4 5))) 1))
  (is (= (content '((:source 1) (2 3) (4 5))) 1))
  (is (= (content '((:target 1) (2 3) (4 5))) 1))
  (is (= (content->elements '(1 (2 3) (4 5)) 4) ['(4 5)]))
  (is (=(entity-key '(1 2)) '(1 2)))
  (is (marked-as-type? '("foo" :label)))
  (is (not (marked-as-type? '("foo" :foo))))
  (is (= (to-list '(nil (1 nil))) '(nil (1 nil)))))

(deftest vector-test
  (is (not (primitive? [:object 1 2])))
  (is (not (element? [:object 1 2])))
  (is (object? [:object 1 2]))
  (is (not (object? [1 2])))
  (is (= (elements [:object 1 2]) [1 2]))
  (is (= (forward-elements [:object 1 2]) [1 2]))
  (is (= (elements '[:object (2 3) (4 5)]) '[(2 3) (4 5)]))
  (is (= (forward-elements '[:object (2 3) (4 5)]) '[(2 3) (4 5)]))
  (is (= (label->elements '[:object (2 (3 :label)) (4 3)] 3)
         '[(2 (3 :label))]))
  (is (= (content [:object 1 2]) nil))
  (is (= (content->elements '[:object (2 3) (4 5)] 4) '[(4 5)]))
  (is (= (entity-key [:object 1 2]) [:object 1 2]))
  (is (not (marked-as-type? [:object 1 2])))
  (is (= (to-list [:object 1 2]) [:object 1 2]))
  ;; More extensive tests of non-identified-object?
  (let [name-label `(~(id->object (make-item-id "name") nil))]
    (is (non-identified-object? [:object]))
    (is (non-identified-object? [:object `(nil ~name-label)]))
    (is (non-identified-object? [:object `("" ~name-label)]))
    (is (non-identified-object? [:object `(~'anything ~name-label)]))
    (is (not (non-identified-object? [:object `("Joe" ~name-label)])))
    (is (not (uniquely-identified-object? [:object])))
    (is (not (uniquely-identified-object? [:object `(nil ~name-label)])))
    (is (not (uniquely-identified-object? [:object `("" ~name-label)])))
    (is (not (uniquely-identified-object? [:object `(~'anything ~name-label)])))
    (is (uniquely-identified-object? [:object `("Joe" ~name-label)]))))

(deftest constant-test
  (is (primitive? 1))
  (is (primitive? true))
  (is (primitive? "foo"))
  (is (primitive? :foo))
  (is (primitive? 'foo))
  (is (primitive? nil))
  (is (primitive? orderable/initial))
  (is (not (element? 1)))
  (is (not (element? true)))
  (is (not (element? "foo")))
  (is (not (element? :foo)))
  (is (not (element? 'foo)))
  (is (not (element? nil)))
  (is (not (element? orderable/initial)))
  (is (not (object? 1)))
  (is (not (object? true)))
  (is (not (object? "foo")))
  (is (not (object? :foo)))
  (is (not (object? 'foo)))
  (is (not (object? nil)))
  (is (not (object? orderable/initial)))
  (is (= (orientation 1) :source))
  (is (= (orientation true) :source))
  (is (= (orientation "foo") :source))
  (is (= (orientation :foo) :source))
  (is (= (orientation 'foo) :source))
  (is (= (orientation nil) :source))
  (is (= (orientation orderable/initial) :source))
  (is (= (content 1) 1))
  (is (= (content true) true))
  (is (= (content "foo") "foo"))
  (is (= (content :foo) :foo))
  (is (= (content 'foo) 'foo))
  (is (= (content nil) nil))
  (is (= (content orderable/initial) orderable/initial))
  (is (= (elements 1) nil))
  (is (= (elements true) nil))
  (is (= (elements "foo") nil))
  (is (= (elements :foo) nil))
  (is (= (elements 'foo) nil))
  (is (= (elements nil) nil))
  (is (= (elements orderable/initial) nil))
  (is (= (forward-elements 1) nil))
  (is (= (forward-elements true) nil))
  (is (= (forward-elements "foo") nil))
  (is (= (forward-elements :foo) nil))
  (is (= (forward-elements 'foo) nil))
  (is (= (forward-elements nil) nil))
  (is (= (forward-elements orderable/initial) nil))
  (is (= (content->elements 1 1) nil))
  (is (= (content->elements true 1) nil))
  (is (= (content->elements "foo" 1) nil))
  (is (= (content->elements :foo 1) nil))
  (is (= (content->elements 'foo 1) nil))
  (is (= (content->elements nil 1) nil))
  (is (= (content->elements orderable/initial 1) nil))
  (is (= (label->elements 1 1) nil))
  (is (= (label->elements true 1) nil))
  (is (= (label->elements "foo" 1) nil))
  (is (= (label->elements :foo 1) nil))
  (is (= (label->elements 'foo 1) nil))
  (is (= (label->elements nil 1) nil))
  (is (= (label->elements orderable/initial 1) nil))
  (is (not (marked-as-type? 1)))
  (is (not (marked-as-type? true)))
  (is (not (marked-as-type? "foo")))
  (is (not (marked-as-type? :foo)))
  (is (not (marked-as-type? 'foo)))
  (is (not (marked-as-type? nil)))
  (is (not (marked-as-type? orderable/initial)))
  (is (= (entity-key 1) 1))
  (is (= (entity-key true) true))
  (is (= (entity-key "foo") "foo"))
  (is (= (entity-key :foo) :foo))
  (is (= (entity-key 'foo) 'foo))
  (is (= (entity-key nil) nil))
  (is (= (entity-key orderable/initial) orderable/initial))
  (is (to-list 3) 3))

(deftest add-elements-to-entity-test
  (is (= (add-elements-to-entity '(1 2 (3 4)) '())
         '(1 2 (3 4))))
  (is (= (add-elements-to-entity '(1 2 (3 4)) '(5 (6 7)))
         '(1 2 (3 4) 5 (6 7))))
  (is (= (add-elements-to-entity (make-element-list :target 1 '(2 (3 4)))
                                 '(5 (6 7)))
         (make-element-list :target 1 '(2 (3 4) 5 (6 7)))))
  (is (= (add-elements-to-entity 1 '(5 (6 7)))
         '(1 5 (6 7))))
  (is (= (add-elements-to-entity (make-object-list '(1 2 (3 4))) '(5 (6 7)))
         (make-object-list '(1 2 (3 4) 5 (6 7))))))

(deftest map-elements-test
  (let [incrementer #(if (number? %) (inc %) %)]
    (is (= (map-elements incrementer '(1 5 (2 3) 4))
           '(1 6 (2 3) 5)))
    (is (= (map-elements incrementer (id->object (make-item-id "foo") nil))
           (id->object (make-item-id "foo") nil)))
    (is (= (map-elements incrementer (make-object-list '(5 (2 3) 4)))
           (make-object-list '(6 (2 3) 5))))))

(deftest post-walk-entity-test
  (is (check (post-walk-entity
              #(cond (number? %) (inc %)
                     (interned-object? %) (id->object (make-item-id "bar") nil)
                     (= % '(3 4)) nil
                     :else %)
              `(1 (2 3)
                  (~(make-object-list
                       `(4 (5 6))))
                  (~(id->object (make-item-id "foo") nil))))
             `(2 (~(make-object-list
                    `(5 (6 7))))
                 (~(id->object (make-item-id "bar") nil))))))

(deftest pre-walk-entity-test
  (is (check (pre-walk-entity
              #(cond (number? %) (inc %)
                     (interned-object? %) (id->object (make-item-id "bar") nil)
                     (= % '(2 3)) nil
                     :else %)
              `(1 (2 3)
                  (~(make-object-list
                     `(4 (5 6))))
                  (~(id->object (make-item-id "foo") nil))))
             `(2 (~(make-object-list
                    `(5 (6 7))))
                 (~(id->object (make-item-id "bar") nil))))))

(deftest entity-complexity-test
  (is (= (entity-complexity "a") 1.0))
  (is (= (entity-complexity nil) 0.3))
  (is (= (entity-complexity '(1 2 "" nil)) (+ 1 (* 0.75 (+ 1 0.4 0.3)))))
  (is (= (entity-complexity '(1 (2 "a"))) (+ 1 (* 0.75 (+ 1 0.75)))))
  (is (= (entity-complexity `(~(make-object-list '(1 2)) (2 "a")))
         (+ 0.3 (* 0.75 (+ 1 1)) (* 0.75 (+ 1 0.75))))))

(deftest marked-as-type?-test
  (is (marked-as-type? '("foo" :label)))
  (is (marked-as-type? '("foo" :label "bar")))
  (is (marked-as-type? '("foo" (:label "bar"))))
  (is (not (marked-as-type? '(:label "foo"))))
  (is (not (marked-as-type? :label)))
  (is (not (marked-as-type? "foo")))
  (is (not (marked-as-type? '("foo"))))
  (is (not (marked-as-type? '("foo" "bar"))))
  (is (not (marked-as-type? '(("foo" ("bar" :label)))))))

(deftest label-object?-test
  (let [special-object (fn [id] (id->object (make-item-id id) nil))]
    (is (label-object? (special-object "name")))
    (is (label-object? (make-object-list
                        `((~(special-object "link-type"))))))
    (is (label-object? (make-object-list
                        `((~(special-object "object-type"))))))
    (is (label-object? (make-object-list
                        `(("fred" ~(special-object "name"))
                          (~(special-object "link-type"))))))
    (is (not (label-object? (make-object-list
                             `((~(special-object "name")))))))
    (is (not (label-object? (make-object-list
                             `(("fred" ~(special-object "name")))))))))

(deftest label-element?-test
  (let [special-object (fn [id] (id->object (make-item-id id) nil))]
    (is (label-element? :foo))
    (is (label-element? '(:foo "foo")))
    (is (label-element? '("foo" :label)))
    (is (label-element? '("foo" :label "bar")))
    (is (label-element? `(~(special-object "name"))))
    (is (not (label-element? `("foo" ~(special-object "name")))))
    (is (not (label-element? :label)))
    (is (not (label-element? "foo")))
    (is (not (label-element? `("foo" ~(special-object "name-type")))))
    (is (not (label-element? `("foo" ~(special-object "link-type")))))
    (is (label-element? `(~(make-object-list
                    `((~(special-object "link-type")))))))
    (is (label-element? `(~(make-object-list
                    `((~(special-object "object-type")))))))
    (is (label-element? `(~(make-object-list
                    `(("fred" ~(special-object "name"))
                      (~(special-object "link-type")))))))
    (is (not (label-element? `(~(make-object-list
                         `((~(special-object "name"))))))))
    (is (not (label-element? `(~(make-object-list
                         `(("fred" ~(special-object "name"))))))))))

(deftest make-element-list-test
  (is (= (make-element-list :source 1 nil)
         1))
  (is (= (make-element-list :source 1 [2])
         '(1 2)))
  (is (= (make-element-list :target 1 nil)
         '((:target 1))))
  (is (= (make-element-list :target 1 [2])
         '((:target 1) 2))))

(deftest make-object-list-test
  (is (= (make-object-list [1])
         [:object 1])))
